# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#   projects
    p1 = Project.create(title: "p1project",position:10,user_id:37)
    p2 = Project.create(title: "p2project",position:11,user_id:37)
    p3 = Project.create(title: "p3project",position:13,user_id:37)
    p4 = Project.create(title: "p4project",position:110,user_id:37)
    p5 = Project.create(title: "p5project",position:14,user_id:37)
    p6 = Project.create(title: "p6project",position:15,user_id:37)
    p7 = Project.create(title: "p8project",position:16,user_id:37)
    p8 = Project.create(title: "p8project",position:17,user_id:37)
    p9 = Project.create(title: "p9project",position:19,user_id:37)
    p10 = Project.create(title: "p10project",position:20,user_id:37)  
    p11= Project.create(title: "p11project",position:30,user_id:38)
    p12 = Project.create(title: "p12project",position:40,user_id:38)
    p13 = Project.create(title: "p13project",position:50,user_id:38)
    p14 = Project.create(title: "p14project",position:60,user_id:38)  
    p15 = Project.create(title: "p15project",position:70,user_id:38)
    p16 = Project.create(title: "p16project",position:21,user_id:38)
    p17 = Project.create(title: "p17project",position:22,user_id:38)
    p18= Project.create(title: "p18project",position:23,user_id:38)
    p19= Project.create(title: "p19project",position:24,user_id:38)
    p20 = Project.create(title: "p20project",position:25,user_id:38)
# tasks

    t2 = Task.create(title: "t1task",description: "Task",is_done: true,project_id:p1.id,user_id:37)
    t3 = Task.create(title: "t2task",description: "Task",is_done: true,project_id:p2.id,user_id:37)
    t1 = Task.create(title: "t3task",description: "Task",is_done: false,project_id:p3.id,user_id:37)
    t4 = Task.create(title: "t4task",description: "Task",is_done: false,project_id:p4.id,user_id:37)
    t5 = Task.create(title: "t5task",description: "Task",is_done: true,project_id:p5.id,user_id:37)
    t6 = Task.create(title: "t6task",description: "Task",is_done: true,project_id:p6.id,user_id:37)
    t7 = Task.create(title: "t7task",description: "Task",is_done: false,project_id:p7.id,user_id:37)
    t8 = Task.create(title: "t8task",description: "Task",is_done: true,project_id:p8.id,user_id:37)
    t9 = Task.create(title: "t9task",description: "Task",is_done: true,project_id:p9.id,user_id:37)
    t10 = Task.create(title: "t10task",description: "Task",is_done: false,project_id:p7.id,user_id:37)
    t11 = Task.create(title: "t11task",description: "Task",is_done: false,project_id:p3.id,user_id:37)
    t12 = Task.create(title: "t12task",description: "Task",is_done: false,project_id:p2.id,user_id:37)
    t13 = Task.create(title: "t13task",description: "Task",is_done: false,project_id:p9.id,user_id:37)
    t14 = Task.create(title: "t14task",description: "Task",is_done: true,project_id:p1.id,user_id:37)
    t15 = Task.create(title: "t15task",description: "Task",is_done: true,project_id:p10.id,user_id:37)
    t16 = Task.create(title: "t16task",description: "Task",is_done: true,project_id:p11.id,user_id:38)
    t17 = Task.create(title: "t17task",description: "Task",is_done: true,project_id:p11.id,user_id:38)
    t18 = Task.create(title: "t18task",description: "Task",is_done: true,project_id:p12.id,user_id:38)
    t19 = Task.create(title: "t19task",description: "Task",is_done: true,project_id:p12.id,user_id:38)
    t20 = Task.create(title: "t20task",description: "Task",is_done: true,project_id:p13.id,user_id:38)
    t21 = Task.create(title: "t21task",description: "Task",is_done: true,project_id:p14.id,user_id:38)
    t22= Task.create(title: "t22task",description: "Task",is_done: true,project_id:p15.id,user_id:38)
    t23= Task.create(title: "t23task",description: "Task",is_done: true,project_id:p16.id,user_id:38)
    t24= Task.create(title: "t24task",description: "Task",is_done: true,project_id:p17.id,user_id:38)
    t25= Task.create(title: "t25task",description: "Task",is_done: true,project_id:p18.id,user_id:38)
    t26 = Task.create(title: "t26task",description: "Task",is_done: true,project_id:p19.id,user_id:38)
    t27= Task.create(title: "t27task",description: "Task",is_done: true,project_id:p20.id,user_id:38)
    t28= Task.create(title: "t28task",description: "Task",is_done: true,project_id:p15.id,user_id:38)
    t29= Task.create(title: "t29task",description: "Task",is_done: true,project_id:p16.id,user_id:38)
    t30 = Task.create(title: "t30task",description: "Task",is_done: true,project_id:p17.id,user_id:38)
    
 #Tags
    ta1 = Tag.create(title:"Tag1",user_id: 37)
    ta2 = Tag.create(title:"Tag2",user_id: 37)
    ta3 = Tag.create(title:"Tag3",user_id: 37)
    ta4 = Tag.create(title:"Tag4",user_id: 37)
    ta5 = Tag.create(title:"Tag5",user_id: 37)
    ta6 = Tag.create(title:"Tag6",user_id: 38)
    ta7= Tag.create(title:"Tag7",user_id: 38)
    ta8 = Tag.create(title:"Tag8",user_id: 38)
    ta9 = Tag.create(title:"Tag9",user_id: 38)
    ta10 = Tag.create(title:"Tag10",user_id: 38)
#TagedTasks
    
    tt1 = TagedTask.create(task_id:t1.id,tag_id:ta1.id)
    tt2 = TagedTask.create(task_id:t2.id,tag_id:ta1.id)
    tt3 = TagedTask.create(task_id:t3.id,tag_id:ta2.id)
    tt4 = TagedTask.create(task_id:t4.id,tag_id:ta2.id)
    tt5 = TagedTask.create(task_id:t5.id,tag_id:ta3.id)
    tt6 = TagedTask.create(task_id:t6.id,tag_id:ta3.id)
    tt7 = TagedTask.create(task_id:t7.id,tag_id:ta4.id)
    tt8 = TagedTask.create(task_id:t8.id,tag_id:ta5.id)
    tt9 = TagedTask.create(task_id:t9.id,tag_id:ta6.id)
    tt10 = TagedTask.create(task_id:t10.id,tag_id:ta7.id)
    tt11= TagedTask.create(task_id:t11.id,tag_id:ta7.id)
    tt12= TagedTask.create(task_id:t12.id,tag_id:ta8.id)
    tt13 = TagedTask.create(task_id:t13.id,tag_id:ta9.id)
    tt14 = TagedTask.create(task_id:t14.id,tag_id:ta9.id)
    tt15 = TagedTask.create(task_id:t15.id,tag_id:ta10.id)
    tt16 = TagedTask.create(task_id:t16.id,tag_id:ta10.id)
    tt17 = TagedTask.create(task_id:t17.id,tag_id:ta8.id)
    tt18 = TagedTask.create(task_id:t18.id,tag_id:ta8.id)
    tt19 = TagedTask.create(task_id:t19.id,tag_id:ta7.id)
    tt20 = TagedTask.create(task_id:t20.id,tag_id:ta6.id)
    tt21= TagedTask.create(task_id:t21.id,tag_id:ta5.id)
    tt22 = TagedTask.create(task_id:t22.id,tag_id:ta4.id)
    tt23 = TagedTask.create(task_id:t23.id,tag_id:ta3.id)
    tt24 = TagedTask.create(task_id:t24.id,tag_id:ta2.id)
    tt25= TagedTask.create(task_id:t25.id,tag_id:ta1.id)
    tt26 = TagedTask.create(task_id:t26.id,tag_id:ta5.id)
    tt27 = TagedTask.create(task_id:t27.id,tag_id:ta6.id)
    tt28 = TagedTask.create(task_id:t28.id,tag_id:ta7.id)
